# Generated by Django 4.1 on 2022-09-24 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("joke", "0004_user_is_active_user_is_staff"),
    ]

    operations = [
        migrations.RemoveField(model_name="user", name="name",),
    ]
