# Generated by Django 4.1 on 2022-09-24 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("joke", "0005_remove_user_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="joke",
            name="answer",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="joke", name="is_used", field=models.BooleanField(default=False),
        ),
    ]
