# Generated by Django 4.1 on 2022-09-24 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("joke", "0006_alter_joke_answer_alter_joke_is_used"),
    ]

    operations = [
        migrations.RenameField(model_name="joke", old_name="author", new_name="user",),
    ]
